<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-CDGUVDP" failures="1" tests="1" name="Default test" time="20.738" errors="0" timestamp="2024-07-04T17:17:53 PET">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="16.042">
    <failure type="java.lang.AssertionError" message="did not expect [2] but found [2]">
      <![CDATA[java.lang.AssertionError: did not expect [2] but found [2]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at org.testng.Assert.assertNotEquals(Assert.java:1535)
at com.juiceshop.steps.OrderHistorySteps.user_takes_a_screenshot_of_the_orders(OrderHistorySteps.java:59)
at âœ½.user takes a screenshot of the orders(file:///C:/Users/USUARIO/eclipse-workspace/ProjectJuiceShop/src/test/resources/features/orderhistory.feature:11)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Default test -->
